version: "3.9"
services:
  teste_google_postgres:
    image: postgres
    platform: linux/amd64
    container_name: teste_google_postgres
    environment:
      POSTGRES_PASSWORD: teste_google
      POSTGRES_HOST_AUTH_METHOD: trust
      HOST: http://192.168.0.107:3000
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data:z

  teste_google:
    build: .
    platform: linux/amd64
    container_name: teste_google
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/var/www/teste_google:z
    ports:
      - "3000:3000"
    depends_on:
      - teste_google_postgres

# docker compose build
# docker compose run --rm teste_google bundle install
# docker compose run --rm teste_google rake db:drop
# docker compose run --rm teste_google rake db:create
# docker compose run --rm teste_google rake db:migrate
# docker compose run --rm teste_google rake seed:migrate
# docker compose run  --rm -p 3000:3000 teste_google rails s -b 0.0.0.0
# docker compose run  --rm teste_google rails c